name: iOS Build & Test with Fastlane

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout code from the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Ruby (Fastlane requires Ruby)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.10'  # Specify the Ruby version to use

      # Step 3: Install Bundler and Fastlane (if using Gemfile)
      - name: Install Bundler & Fastlane
        run: |
          bundle install 
          gem install bundler

      # Step 4: Build and Test using Fastlane
      - name: Run Fastlane Build
        run: |
          bundle exec fastlane testFastlane  # Replace 'build' with your Fastlane lane name

     
